# Generated by Django 4.1.5 on 2023-01-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_original', models.FileField(blank=True, upload_to='test_files/', verbose_name='File')),
                ('file_test', models.FileField(blank=True, upload_to='test_files/', verbose_name='File')),
            ],
        ),
    ]
