# Generated by Django 4.1.5 on 2023-01-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_alter_filemodel_file_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_original',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_test',
            field=models.FileField(blank=True, null=True, upload_to='test_files/'),
        ),
    ]
